#!/bin/bash
# Render Deployment Checklist

echo "🚀 Render Deployment Checklist"
echo "=============================="
echo ""
echo "✅ Step 1: Ensure your code is in Git"
echo "   Run: git push origin main"
echo ""
echo "✅ Step 2: Create PostgreSQL database on Render"
echo "   - Go to render.com"
echo "   - Click: New → PostgreSQL"
echo "   - Copy the Internal Database URL"
echo ""
echo "✅ Step 3: Create Web Service on Render"
echo "   - GitHub Repository: (select your repo)"
echo "   - Name: elonu-elon-web"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm run server"
echo ""
echo "✅ Step 4: Set Environment Variables in Render"
echo "   - DATABASE_URL: (from PostgreSQL service)"
echo "   - JWT_SECRET: (generate strong random string)"
echo "   - ADMIN_KEY: (generate strong random string)"
echo "   - NODE_ENV: production"
echo "   - PORT: 5001"
echo ""
echo "✅ Step 5: Deploy"
echo "   - Click 'Create Web Service'"
echo "   - Wait for deployment (2-5 minutes)"
echo ""
echo "✅ Step 6: Test"
echo "   - Visit your Render URL"
echo "   - Log in and test features"
echo "   - Check admin panel"
echo ""
echo "📖 Full guide: See RENDER_DEPLOYMENT.md"
